export const MemberData = [
    {
        id: 1,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Ricky",
        lastName: "Thoudam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 2,
            image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Dexter",
        lastName: "Thoudam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 3,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Naorem",
        lastName: "Diyabarta",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 4,
        image: require('../assets/testimonalImg/avatar2.jpg'),
        firstName: "Liya",
        lastName: "Meisnam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 5,
        image: require('../assets/testimonalImg/avatar2.jpg'),
        firstName: "Pinky",
        lastName: "Thokchom",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 6,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Langamba",
        lastName: "Naoroibam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 7,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Oinam",
        lastName: "Diamond",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 8,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Asem",
        lastName: "Ajay",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 9,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Gaithoijin",
        lastName: "Panmei",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 10,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Akash",
        lastName: "Sagolshem",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 11,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Abheejit",
        lastName: "Thokchom",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 12,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Bronson",
        lastName: "Khundrakpam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 13,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Hidangmayum",
        lastName: "Durge",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 14,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Asem",
        lastName: "Ajay",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 15,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Christopher",
        lastName: "Charang",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 16,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Leineikhup",
        lastName: "Serto",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 17,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Thanring",
        lastName: "Homung",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 18,
        image: require('../assets/testimonalImg/avatar2.jpg'),
        firstName: "Reya",
        lastName: "Salam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 19,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Akoijam",
        lastName: "Lenin",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 20,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Shrey kumar",
        lastName: "Sahu",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 21,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Hillary",
        lastName: "Chawang",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 22,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Rakesh",
        lastName: "Sanasam",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 23,
        image: require('../assets/testimonalImg/avatar4.jpg'),
        firstName: "Yumkhaibam",
        lastName: "Yahiya",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 24,
        image: require('../assets/testimonalImg/avatar3.jpg'),
        firstName: "Nameirakpam",
        lastName: "Khirol",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    {
        id: 25,
        image: require('../assets/testimonalImg/avatar1.jpg'),
        firstName: "Soudulou",
        lastName: "Duomai",
        batch: "2021",
        branch: "Computer Science & Engineering",
    },
    
]